""" added index on date attrib

Revision ID: 01656ac93e8b
Revises: 8ee7611db673
Create Date: 2026-04-09 20:29:51.095215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01656ac93e8b'
down_revision: Union[str, Sequence[str], None] = '8ee7611db673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_date'), 'sessions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_date'), table_name='sessions')
    # ### end Alembic commands ###
