"""added vector embeddings

Revision ID: 162fa542daf9
Revises: 8e3ecdd528c2
Create Date: 2026-07-09 11:28:36.196224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  



# revision identifiers, used by Alembic.
revision: str = '162fa542daf9'
down_revision: Union[str, Sequence[str], None] = '8e3ecdd528c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk', 'embedding')
    # ### end Alembic commands ###
