"""added new table with relationship

Revision ID: 636ee1392416
Revises: 01656ac93e8b
Create Date: 2026-04-14 16:39:28.813456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636ee1392416'
down_revision: Union[str, Sequence[str], None] = '01656ac93e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_sessions', sa.String(length=255), nullable=False),
    sa.Column('total_minutes', sa.String(length=255), nullable=False),
    sa.Column('top_project', sa.String(length=255), nullable=True),
    sa.Column('most_common_blocker', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_summaries')
    # ### end Alembic commands ###
