"""add summary to workspace

Revision ID: 8e3bcdfd2cee
Revises: a5ee50e47b8f
Create Date: 2026-07-06 11:49:24.416917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3bcdfd2cee'
down_revision: Union[str, Sequence[str], None] = 'a5ee50e47b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_workspace_description'), table_name='workspace')
    op.drop_constraint(op.f('uq_workspace'), 'workspace', type_='unique')
    op.create_index(op.f('ix_workspace_summary'), 'workspace', ['summary'], unique=False)
    op.drop_column('workspace', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_workspace_summary'), table_name='workspace')
    op.create_unique_constraint(op.f('uq_workspace'), 'workspace', ['name', 'owner_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_workspace_description'), 'workspace', ['description'], unique=False)
    op.drop_column('workspace', 'summary')
    # ### end Alembic commands ###
