"""added parsed_markdown to document table

Revision ID: 8e3ecdd528c2
Revises: 8e3bcdfd2cee
Create Date: 2026-07-06 17:44:55.571482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3ecdd528c2'
down_revision: Union[str, Sequence[str], None] = '8e3bcdfd2cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'parsed_markdown')
    # ### end Alembic commands ###
