"""add status to sessions

Revision ID: d82a16f8c69f
Revises: 2b47130769c6
Create Date: 2026-04-21 13:59:59.076369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82a16f8c69f'
down_revision: Union[str, Sequence[str], None] = '2b47130769c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.String(length=50), nullable=False, server_default='completed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
